language: node_js

node_js: stable

branches:
  only:
  - master

before_install:
- openssl aes-256-cbc -K $encrypted_750171d8cb6d_key -iv $encrypted_750171d8cb6d_iv
  -in travis_id_rsa.enc -out ~/.ssh/id_rsa -d

addons:
  ssh_known_hosts: 50.116.36.79

after_success:
- ssh root@50.116.36.79 'cd /home/github/blog && git pull'
