name: Publisher

on: 
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish
    runs-on: self-hosted
    steps:
      - name: Checkout code
        run: pwd && cd github/blog && git pull