name: Publisher

on: 
  push:
    branches: [ master ]

jobs:
  publish:
    name: Publish
    runs-on: self-hosted
    steps:
      - name: Checkout code
        run: cd /root/github/blog && git pull && cd /root/hexo && hexo g